# Generated by Django 2.2.5 on 2020-05-22 02:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eds_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='users_report',
            new_name='users_type_permission',
        ),
    ]
