# Generated by Django 2.2.5 on 2020-05-22 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eds_app', '0006_user_report_users_type_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='passwd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50, null=True)),
                ('username', models.CharField(max_length=50, null=True)),
                ('umail', models.CharField(max_length=50, null=True)),
                ('date', models.DateTimeField(null=True)),
            ],
        ),
    ]
