# Generated by Django 2.2.5 on 2020-05-22 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eds_app', '0007_passwd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users_type_permission',
            name='userid',
        ),
        migrations.DeleteModel(
            name='user_report',
        ),
        migrations.DeleteModel(
            name='users_type_permission',
        ),
    ]
