# Generated by Django 2.2.5 on 2020-05-22 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eds_app', '0009_user_report_users_type_permission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users_type_permission',
            old_name='userid',
            new_name='user_id',
        ),
    ]
